dateImages(ActionContributionItem.java:1016)
	at org.eclipse.jface.action.ActionContributionItem.updateToolItem(ActionContributionItem.java:776)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:739)
	at org.eclipse.jface.action.ActionContributionItem.fill(ActionContributionItem.java:350)
	at org.eclipse.jface.action.SubContributionItem.fill(SubContributionItem.java:75)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:358)
	at org.eclipse.ui.internal.e4.compatibility.ActionBars.updateActionBars(ActionBars.java:68)
	at org.eclipse.ui.part.PageBookView.showPageRec(PageBookView.java:937)
	at org.eclipse.ui.internal.console.ConsoleView.showPageRec(ConsoleView.java:169)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:701)
	at org.eclipse.ui.internal.console.ConsoleView.lambda$0(ConsoleView.ja